import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <nav className="flex justify-around bg-black text-white">
          <Link href="/"> home</Link>
          <Link href="/blog"> blog</Link>
          <Link href="/yolo"> swag</Link>
          <Link href="/yolo"> yolo</Link>
        </nav>
        <div className="container mx-auto h-40 flex flex-row justify-between  gap-2.5	">
          <div className="h-full bg-blue-400 flex-1" />
          <div className="h-full bg-blue-400 flex-1" />
          <div className="h-full bg-blue-400 flex-1" />
        </div>
      </main>
    </>
  );
};

export default Home;
